# Google Cloud Build configuration for deploying to Cloud Run
# Usage: gcloud builds submit --config cloudbuild.yaml

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/from-air-to-care-api:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/from-air-to-care-api:latest'
      - '.'

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/from-air-to-care-api'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'from-air-to-care-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/from-air-to-care-api:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'PYTHONUNBUFFERED=1'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/from-air-to-care-api:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/from-air-to-care-api:latest'

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

